<?php
/**
 * Created by PhpStorm.
 * User: linyang
 * Date: 16/10/31
 * Time: 上午11:44
 */

namespace com\cube\middleware;

use com\cube\core\Application;
use com\cube\core\Request;
use com\cube\core\Response;

/**
 * Class RouterMiddleWare.
 * the middleware of the router connect.
 * @package com\cube\middleware
 */
class RouterMiddleWare
{
    /**
     * Application Instance.
     * @var
     */
    protected $app;

    /**
     * RouterMiddleWare constructor.
     * @param $filter router filter
     */
    public function __construct($filter)
    {
        $this->app = Application::getInstance();

        //router instance instead of router className.
        $this->app->on($filter, $this);
    }

    /**
     * execute router middleware
     * @param Request $req
     * @param Response $res
     * @param Connect $connect
     */
    public function run(Request $req, Response $res, Connect $connect)
    {
        parent::run($req, $res, $connect); // TODO: Change the autogenerated stub

        $connect->next();
    }

    /**
     * the middleware execute end.
     */
    public function end()
    {
        //need override.
    }
}